### ISSUE TITLE
Humanize group name in message

### ISSUE THREAD

**Issue by tuxagon** [testdouble/double-up#19]
The current message will use the key of the grouping from the matchmaking config file. Possibly add a new field or use something from ActiveSupport to humanize it to something like 

* rotating_brunch => Rotating Brunch
* coffee_time => Coffee Time
* q_branch => Q Branch

The inflector might be the easiest way https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-humanize

**Comment by cpruitt** [comment]
Closed by https://github.com/testdouble/double-up/pull/35
