### ISSUE TITLE
Notifications should be sent via email when matches are made

### ISSUE THREAD

**Issue by cpruitt** [testdouble/double-up#31]
Currently when we build matches, we notify folks via a group DM in slack. Some people miss them. Some people dislike them. While I don't think we're gonna turn off the DMs for now, we'd like to also send emails for notifications.

**ASSUMPTION: All Slack accounts use a Test Double email address that the user will see emails for or, if not, those people can rely on DMs.**

When matches are made we'll want to use the slack API to collect email addresses form the [users.info endpoint](https://api.slack.com/methods/users.info). Note the callout on the linked page that talks about the auth scope requirements.

**Comment by tuxagon** [comment]
#43 and #39 introduced emailing
